"""empty message

Revision ID: 296584f3a5a3
Revises: aba3786b8948
Create Date: 2021-03-29 02:47:00.284177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296584f3a5a3'
down_revision = 'aba3786b8948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'message')
    # ### end Alembic commands ###
