"""empty message

Revision ID: 29d9aeef7815
Revises: 296584f3a5a3
Create Date: 2021-03-29 03:02:53.423656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d9aeef7815'
down_revision = '296584f3a5a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'message', 'room', ['room_id'], ['id'])
    # ### end Alembic commands ###
