"""empty message

Revision ID: 36366fa876f3
Revises: d04af19a7c61
Create Date: 2021-03-29 03:45:09.114555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36366fa876f3'
down_revision = 'd04af19a7c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userroom', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userroom', sa.Column('message', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
