"""empty message

Revision ID: 79c338017e2b
Revises: d7c4d82f65ae
Create Date: 2021-05-01 21:21:56.416610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c338017e2b'
down_revision = 'd7c4d82f65ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('message', sa.Column('time_stamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'time_stamp')
    op.drop_column('message', 'content')
    # ### end Alembic commands ###
