"""empty message

Revision ID: aba3786b8948
Revises: c9df7fb09b77
Create Date: 2021-03-29 02:40:09.834594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba3786b8948'
down_revision = 'c9df7fb09b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'message')
    # ### end Alembic commands ###
