"""empty message

Revision ID: d7c4d82f65ae
Revises: 66bb8fe509fe
Create Date: 2021-03-30 00:15:54.676354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c4d82f65ae'
down_revision = '66bb8fe509fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('time_stamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'time_stamp')
    # ### end Alembic commands ###
